export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/intro.html.js"), meta: {"cover":"/assets/images/cover3.jpg","excerpt":"\n<ul>\n<li>\n<p><strong>姓名</strong>: 骆裕</p>\n</li>\n<li>\n<p><strong>全网圈名、网名</strong>: 明裕、明裕学长、明裕吖</p>\n</li>\n<li>\n<p><strong>政治面貌</strong>:中共预备党员</p>\n</li>\n<li>\n<p><strong>出生日期</strong>: 2004-09-30</p>\n</li>\n<li>\n<p><strong>所属机构</strong>: 明裕学长工作室</p>\n</li>\n<li>\n<p><strong>联系方式</strong>:</p>\n<ul>\n<li>Outlook 邮箱: <a href=\"mailto:mingyuxuezhang@outlook.com\" target=\"_blank\" rel=\"noopener noreferrer\">mingyuxuezhang@outlook.com</a></li>\n<li>Gmail: <a href=\"mailto:luoyu2004@gmail.com\" target=\"_blank\" rel=\"noopener noreferrer\">luoyu2004@gmail.com</a></li>\n<li>QQ邮箱: <a href=\"mailto:mingyuxuezhang@qq.com\" target=\"_blank\" rel=\"noopener noreferrer\">mingyuxuezhang@qq.com</a></li>\n</ul>\n</li>\n<li>\n<p><strong>爱好</strong>: 音乐、追剧、技术</p>\n</li>\n</ul>","readingTime":{"minutes":0.29,"words":87},"title":"介绍页","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/index.html.js"), meta: {"title":"主页","icon":"house"} }],
  ["/about/", { loader: () => import(/* webpackChunkName: "about_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/about/index.html.js"), meta: {"category":["关于我","个人简历"],"tag":["个人简历"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<ul>\n<li>\n<p><strong>姓名</strong>: 骆裕</p>\n</li>\n<li>\n<p><strong>全网圈名、网名</strong>: 明裕、明裕学长、明裕吖</p>\n</li>\n<li>\n<p><strong>政治面貌</strong>:中共预备党员</p>\n</li>\n<li>\n<p><strong>出生日期</strong>: 2004-09-30</p>\n</li>\n<li>\n<p><strong>所属机构</strong>: 明裕学长工作室</p>\n</li>\n<li>\n<p><strong>联系方式</strong>:</p>\n<ul>\n<li>Outlook 邮箱: <a href=\"mailto:mingyuxuezhang@outlook.com\" target=\"_blank\" rel=\"noopener noreferrer\">mingyuxuezhang@outlook.com</a></li>\n<li>Gmail: <a href=\"mailto:luoyu2004@gmail.com\" target=\"_blank\" rel=\"noopener noreferrer\">luoyu2004@gmail.com</a></li>\n<li>QQ邮箱: <a href=\"mailto:mingyuxuezhang@qq.com\" target=\"_blank\" rel=\"noopener noreferrer\">mingyuxuezhang@qq.com</a></li>\n</ul>\n</li>\n<li>\n<p><strong>爱好</strong>: 音乐、追剧、技术</p>\n</li>\n</ul>","readingTime":{"minutes":0.37,"words":112},"title":"关于我","icon":"laptop-code","type":"article"} }],
  ["/notes/", { loader: () => import(/* webpackChunkName: "notes_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/notes/index.html.js"), meta: {"category":["生活随笔"],"readingTime":{"minutes":0.06,"words":17},"title":"生活随笔","icon":"laptop-code","type":"article"} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/index.html.js"), meta: {"category":["知识库目录"],"readingTime":{"minutes":0.06,"words":19},"title":"知识库目录","icon":"laptop-code","type":"article"} }],
  ["/about/%E9%9F%B3%E4%B9%90/0-%E8%96%9B%E4%B9%8B%E8%B0%A6.html", { loader: () => import(/* webpackChunkName: "about_音乐_0-薛之谦.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/about/音乐/0-薛之谦.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.15,"words":44},"title":"薛之谦的歌单","icon":"pen-to-square","type":"article"} }],
  ["/about/%E9%9F%B3%E4%B9%90/", { loader: () => import(/* webpackChunkName: "about_音乐_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/about/音乐/index.html.js"), meta: {"category":["音乐推荐"],"excerpt":"\n","readingTime":{"minutes":0.07,"words":21},"title":"音乐推荐","icon":"laptop-code","type":"article"} }],
  ["/about/%E8%BF%BD%E5%89%A7/0-%E5%BC%A0%E8%8B%A5%E6%98%80.html", { loader: () => import(/* webpackChunkName: "about_追剧_0-张若昀.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/about/追剧/0-张若昀.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.14,"words":43},"title":"张若昀的剧","icon":"pen-to-square","type":"article"} }],
  ["/about/%E8%BF%BD%E5%89%A7/", { loader: () => import(/* webpackChunkName: "about_追剧_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/about/追剧/index.html.js"), meta: {"category":["追剧推荐"],"excerpt":"\n","readingTime":{"minutes":0.07,"words":21},"title":"追剧推荐","icon":"laptop-code","type":"article"} }],
  ["/posts/%E5%89%8D%E7%AB%AF%E6%8A%80%E6%9C%AF/0-%E5%89%8D%E7%AB%AF%E4%B8%89%E5%89%91%E5%AE%A2.html", { loader: () => import(/* webpackChunkName: "posts_前端技术_0-前端三剑客.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/前端技术/0-前端三剑客.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.14,"words":43},"title":"前端三剑客","icon":"pen-to-square","type":"article"} }],
  ["/posts/%E5%89%8D%E7%AB%AF%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "posts_前端技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/前端技术/index.html.js"), meta: {"category":["前端技术"],"readingTime":{"minutes":0.06,"words":17},"title":"前端技术","icon":"laptop-code","type":"article"} }],
  ["/posts/%E5%AE%89%E5%85%A8%E6%8A%80%E6%9C%AF/0-%E6%B0%B8%E6%81%92%E4%B9%8B%E8%93%9Dms17_010.html", { loader: () => import(/* webpackChunkName: "posts_安全技术_0-永恒之蓝ms17_010.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/安全技术/0-永恒之蓝ms17_010.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.15,"words":44},"title":"永恒之蓝ms17-010","icon":"pen-to-square","type":"article"} }],
  ["/posts/%E5%AE%89%E5%85%A8%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "posts_安全技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/安全技术/index.html.js"), meta: {"category":["安全技术"],"readingTime":{"minutes":0.06,"words":17},"title":"安全技术","icon":"laptop-code","type":"article"} }],
  ["/posts/%E5%90%8E%E7%AB%AF%E6%8A%80%E6%9C%AF/0-Java%E5%85%A5%E9%97%A8.html", { loader: () => import(/* webpackChunkName: "posts_后端技术_0-Java入门.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/后端技术/0-Java入门.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.14,"words":41},"title":"Java入门","icon":"pen-to-square","type":"article"} }],
  ["/posts/%E5%90%8E%E7%AB%AF%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "posts_后端技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/后端技术/index.html.js"), meta: {"category":["后端技术"],"readingTime":{"minutes":0.06,"words":17},"title":"后端技术","icon":"laptop-code","type":"article"} }],
  ["/posts/%E8%BF%90%E7%BB%B4%E6%8A%80%E6%9C%AF/0-Windows%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.html", { loader: () => import(/* webpackChunkName: "posts_运维技术_0-Windows操作系统.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/运维技术/0-Windows操作系统.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.14,"words":43},"title":"Windows操作系统","icon":"pen-to-square","type":"article"} }],
  ["/posts/%E8%BF%90%E7%BB%B4%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "posts_运维技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/运维技术/index.html.js"), meta: {"category":["运维技术"],"readingTime":{"minutes":0.06,"words":17},"title":"运维技术","icon":"laptop-code","type":"article"} }],
  ["/posts/VPS%E6%8A%80%E6%9C%AF/0-%E4%BD%BF%E7%94%A8hiddify%E7%A7%91%E5%AD%A6%E4%B8%8A%E7%BD%91.html", { loader: () => import(/* webpackChunkName: "posts_VPS技术_0-使用hiddify科学上网.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/VPS技术/0-使用hiddify科学上网.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["没想好"],"tag":["没想好"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.15,"words":45},"title":"使用hiddify科学上网","icon":"pen-to-square","type":"article"} }],
  ["/posts/VPS%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "posts_VPS技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/posts/VPS技术/index.html.js"), meta: {"category":["VPS技术"],"readingTime":{"minutes":0.05,"words":15},"title":"VPS技术","icon":"laptop-code","type":"article"} }],
  ["/notes/2025/03/20250319-%E5%8D%9A%E5%AE%A2%E5%92%8C%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86%E6%90%AD%E5%BB%BA%E4%B9%8B%E6%97%85.html", { loader: () => import(/* webpackChunkName: "notes_2025_03_20250319-博客和个人简历搭建之旅.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/notes/2025/03/20250319-博客和个人简历搭建之旅.html.js"), meta: {"date":1742342400000,"localizedDate":"2025年3月19日","category":["系统部署"],"tag":["博客","个人简历"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.18,"words":53},"title":"博客和个人简历搭建之旅","icon":"pen-to-square","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/notes/2025/03/", { loader: () => import(/* webpackChunkName: "notes_2025_03_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/notes/2025/03/index.html.js"), meta: {"title":"03"} }],
  ["/notes/2025/", { loader: () => import(/* webpackChunkName: "notes_2025_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/notes/2025/index.html.js"), meta: {"title":"2025"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E5%85%B3%E4%BA%8E%E6%88%91/", { loader: () => import(/* webpackChunkName: "category_关于我_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/关于我/index.html.js"), meta: {"title":"关于我 分类","index":false} }],
  ["/category/%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86/", { loader: () => import(/* webpackChunkName: "category_个人简历_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/个人简历/index.html.js"), meta: {"title":"个人简历 分类","index":false} }],
  ["/category/%E7%94%9F%E6%B4%BB%E9%9A%8F%E7%AC%94/", { loader: () => import(/* webpackChunkName: "category_生活随笔_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/生活随笔/index.html.js"), meta: {"title":"生活随笔 分类","index":false} }],
  ["/category/%E7%9F%A5%E8%AF%86%E5%BA%93%E7%9B%AE%E5%BD%95/", { loader: () => import(/* webpackChunkName: "category_知识库目录_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/知识库目录/index.html.js"), meta: {"title":"知识库目录 分类","index":false} }],
  ["/category/%E6%B2%A1%E6%83%B3%E5%A5%BD/", { loader: () => import(/* webpackChunkName: "category_没想好_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/没想好/index.html.js"), meta: {"title":"没想好 分类","index":false} }],
  ["/category/%E9%9F%B3%E4%B9%90%E6%8E%A8%E8%8D%90/", { loader: () => import(/* webpackChunkName: "category_音乐推荐_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/音乐推荐/index.html.js"), meta: {"title":"音乐推荐 分类","index":false} }],
  ["/category/%E8%BF%BD%E5%89%A7%E6%8E%A8%E8%8D%90/", { loader: () => import(/* webpackChunkName: "category_追剧推荐_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/追剧推荐/index.html.js"), meta: {"title":"追剧推荐 分类","index":false} }],
  ["/category/%E5%89%8D%E7%AB%AF%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "category_前端技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/前端技术/index.html.js"), meta: {"title":"前端技术 分类","index":false} }],
  ["/category/%E5%AE%89%E5%85%A8%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "category_安全技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/安全技术/index.html.js"), meta: {"title":"安全技术 分类","index":false} }],
  ["/category/%E5%90%8E%E7%AB%AF%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "category_后端技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/后端技术/index.html.js"), meta: {"title":"后端技术 分类","index":false} }],
  ["/category/%E8%BF%90%E7%BB%B4%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "category_运维技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/运维技术/index.html.js"), meta: {"title":"运维技术 分类","index":false} }],
  ["/category/vps%E6%8A%80%E6%9C%AF/", { loader: () => import(/* webpackChunkName: "category_vps技术_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/vps技术/index.html.js"), meta: {"title":"VPS技术 分类","index":false} }],
  ["/category/%E7%B3%BB%E7%BB%9F%E9%83%A8%E7%BD%B2/", { loader: () => import(/* webpackChunkName: "category_系统部署_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/category/系统部署/index.html.js"), meta: {"title":"系统部署 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86/", { loader: () => import(/* webpackChunkName: "tag_个人简历_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/tag/个人简历/index.html.js"), meta: {"title":"标签: 个人简历","index":false} }],
  ["/tag/%E6%B2%A1%E6%83%B3%E5%A5%BD/", { loader: () => import(/* webpackChunkName: "tag_没想好_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/tag/没想好/index.html.js"), meta: {"title":"标签: 没想好","index":false} }],
  ["/tag/%E5%8D%9A%E5%AE%A2/", { loader: () => import(/* webpackChunkName: "tag_博客_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/tag/博客/index.html.js"), meta: {"title":"标签: 博客","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/LEARN/MY-Project/MYXZ-Blog/blog/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
