export const themeData = JSON.parse("{\"encrypt\":{\"config\":{}},\"author\":{\"name\":\"明裕学长\",\"url\":\"\"},\"logo\":\"https://i.stardots.io/myxz/明裕的小窝.png?width=500&rotate=0&blur=0&quality=50\",\"repo\":\"/China-MY/\",\"docsDir\":\"blog\",\"fullscreen\":true,\"footer\":\"2025 by 明裕的小窝\",\"displayFooter\":true,\"blog\":{\"description\":\"抱利他之心，行利他之事~\",\"intro\":\"/intro.html\",\"medias\":{\"Baidu\":\"https://tieba.baidu.com/home/main?un=%E6%98%8E%E8%A3%95%E5%AD%A6%E9%95%BF\",\"BiliBili\":\"https://space.bilibili.com/483865298\",\"Discord\":\"https://discord.gg/vqsmJjPm\",\"Email\":\"mingyuxuezhang@qq.com\",\"Gitee\":\"https://gitee.com/myxzgzs\",\"GitHub\":\"https://github.com/China-MY\",\"Gmail\":\"luoyu2004@gmail.com\",\"Instagram\":\"http://t.me/myxz2004\",\"QQ\":\"http://1792943568.qzone.qq.com\",\"Steam\":\"https://steamcommunity.com/id/MYXZ/\",\"Twitter\":\"https://x.com/mngyxuzhng1?t=28LNIWGEDBJ8NNcTlcEvbQ&s=09\",\"Wechat\":\"https://ptnk.bmwwx.cn/TuwmzT\",\"Weibo\":\"https://weibo.com/u/7531805872\",\"Whatsapp\":\"https://wa.me/qr/LEUK5FT77O32A1\",\"Youtube\":\"https://www.youtube.com/@%E6%98%8E%E8%A3%95%E5%AD%A6%E9%95%BF\",\"Zhihu\":\"https://www.zhihu.com/people/ai-wan-you-xi-de-xiao-hai-tun\",\"Rss\":\"https://resume.myxz.fun\"}},\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\",\"print\":\"打印\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"星标\",\"empty\":\"$text 为空\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\"},\"navbar\":[\"/\"],\"sidebar\":{\"/\":[\"\",{\"text\":\"文章\",\"icon\":\"book\",\"prefix\":\"posts/\",\"children\":\"structure\"}]}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
